import fs from 'node:fs';
import { execFileOff } from '../spawnOff.ts';
import path from 'node:path';
import { CLI_PATH, DATA_DIR, DAEMON_URL, IS_WINDOWS, ensureDirs } from '../config.ts';
import type { ServiceStatus } from '../shared/types.ts';
import * as systemd from './systemd.ts';

const IS_LINUX = process.platform === 'linux';

/** What the last install had to say that the operator should act on (Linux: lingering, tmux). */
let installNotes: string[] = [];
export function lastInstallNotes(): string[] {
  return installNotes;
}

const run = execFileOff;

/**
 * What the logon task keeps running: the daemon, on the hub, or the desk agent, on a satellite. A
 * machine is one or the other, so installing one role removes the other's task.
 */
export type ServiceRole = 'daemon' | 'desk';

export const TASK_NAME = 'Switchboard daemon';
const TASK_NAMES: Record<ServiceRole, string> = { daemon: TASK_NAME, desk: 'Switchboard desk' };
const files = (role: ServiceRole): { launcher: string; runner: string; log: string } => ({
  launcher: path.join(DATA_DIR, `switchboard-${role}.vbs`),
  runner: path.join(DATA_DIR, `switchboard-${role}.cmd`),
  log: path.join(DATA_DIR, `${role}.log`),
});
const LAUNCHER = files('daemon').launcher;

export function taskName(role: ServiceRole): string {
  return IS_LINUX ? systemd.unitName(role) : TASK_NAMES[role];
}

export function serviceLog(role: ServiceRole): string {
  return files(role).log;
}

function ps(script: string): Promise<{ stdout: string; stderr: string }> {
  return run('powershell.exe', ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-Command', script], {
    timeout: 60_000,
    windowsHide: true,
  });
}

/**
 * A supervisor script rather than a bare command: it keeps the daemon hidden (no console window
 * on every logon) and restarts it if it ever exits. Task Scheduler's own restart-on-failure
 * cannot do this job, because a task that launches a detached process is considered finished
 * immediately.
 */
function launcherScript(role: ServiceRole): string {
  // Run the batch file, not the command directly: `cmd /c "quoted exe" ...` mangles its own
  // quoting, and a one-line batch file sidesteps the whole nested-quote problem.
  return [
    "' Generated by: switchboard service install",
    'Set sh = CreateObject("WScript.Shell")',
    'Do',
    `  sh.Run """${files(role).runner}""", 0, True`,
    '  WScript.Sleep 10000',
    'Loop',
    '',
  ].join('\r\n');
}

function runnerScript(role: ServiceRole): string {
  const log = files(role).log;
  return [
    '@echo off',
    'rem Generated by: switchboard service install',
    `echo [%date% %time%] starting switchboard ${role}>> "${log}"`,
    `"${process.execPath}" "${CLI_PATH}" ${role} >> "${log}" 2>&1`,
    `echo [%date% %time%] ${role} exited with %ERRORLEVEL%>> "${log}"`,
    '',
  ].join('\r\n');
}

/** True when a supervisor script is installed, so the daemon comes back if it exits. */
export function isSupervised(): boolean {
  return IS_LINUX ? fs.existsSync(path.join(process.env.XDG_CONFIG_HOME || path.join(process.env.HOME ?? '', '.config'), 'systemd', 'user', systemd.unitName('daemon'))) : fs.existsSync(LAUNCHER);
}

export async function serviceStatus(role: ServiceRole = 'daemon'): Promise<ServiceStatus> {
  if (IS_LINUX) return systemd.status(role);
  const status: ServiceStatus = {
    supported: IS_WINDOWS,
    installed: false,
    state: null,
    lastRunTime: null,
    lastResult: null,
    running: false,
    logPath: files(role).log,
  };
  try {
    const res = await fetch(`${role === 'desk' ? (process.env.SWITCHBOARD_DESK_URL ?? DAEMON_URL) : DAEMON_URL}/healthz`, { signal: AbortSignal.timeout(2000) });
    status.running = res.ok;
  } catch {
    status.running = false;
  }
  if (!IS_WINDOWS) return status;
  try {
    const { stdout } = await ps(
      `$t = Get-ScheduledTask -TaskName '${TASK_NAMES[role]}' -ErrorAction SilentlyContinue; ` +
        `if ($t) { $i = $t | Get-ScheduledTaskInfo; ` +
        `@{ state = $t.State.ToString(); lastRunTime = $(if ($i.LastRunTime) { $i.LastRunTime.ToString('o') } else { $null }); lastResult = $i.LastTaskResult.ToString() } | ConvertTo-Json -Compress }`,
    );
    const text = stdout.trim();
    if (text) {
      const info = JSON.parse(text) as { state?: string; lastRunTime?: string; lastResult?: string };
      status.installed = true;
      status.state = info.state ?? null;
      status.lastRunTime = info.lastRunTime ?? null;
      status.lastResult = info.lastResult ?? null;
    }
  } catch {
    // Task Scheduler unavailable: report as not installed
  }
  return status;
}

/**
 * Register a logon task that keeps the daemon running.
 *
 * It is a *logon* task, not a startup one, on purpose: opening Windows Terminal tabs needs an
 * interactive desktop, which a session-0 service does not have. After an unattended reboot the
 * daemon therefore comes back when the desk signs in.
 */
export async function installService(delaySeconds = 20, role: ServiceRole = 'daemon'): Promise<ServiceStatus> {
  if (IS_LINUX) {
    const r = await systemd.install(role);
    installNotes = r.notes;
    return r.status;
  }
  installNotes = [];
  if (!IS_WINDOWS) throw Object.assign(new Error('Automatic start is implemented for Windows Task Scheduler and Linux systemd only.'), { status: 400 });
  ensureDirs();
  const other: ServiceRole = role === 'daemon' ? 'desk' : 'daemon';
  // One role per machine: a hub that becomes a satellite stops starting its daemon, and back.
  await ps(`Unregister-ScheduledTask -TaskName '${TASK_NAMES[other]}' -Confirm:$false -ErrorAction SilentlyContinue`).catch(() => undefined);
  fs.rmSync(files(other).launcher, { force: true });
  fs.rmSync(files(other).runner, { force: true });
  const { launcher: LAUNCHER, runner: RUNNER } = files(role);
  fs.writeFileSync(RUNNER, runnerScript(role), 'utf8');
  fs.writeFileSync(LAUNCHER, launcherScript(role), 'utf8');
  const delay = `PT${Math.max(0, Math.round(delaySeconds))}S`;
  const script = [
    `$action = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument '"${LAUNCHER}"'`,
    `$trigger = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\\$env:USERNAME"`,
    `$trigger.Delay = '${delay}'`,
    // Never stop it: not on battery, not after 3 days, not when the machine looks idle.
    `$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable ` +
      `-ExecutionTimeLimit ([TimeSpan]::Zero) -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1) -MultipleInstances IgnoreNew`,
    `$settings.DisallowStartOnRemoteAppSession = $false`,
    `$settings.StopIfGoingOnBatteries = $false`,
    /*
     * Normal priority, not Task Scheduler's default of 7.
     *
     * 7 reads like a CPU hint and is much more than that: Windows starts the task below normal on
     * CPU, and at low memory priority and low I/O priority as well. For a batch job that is right.
     * For the daemon it is backwards — every hook from every session waits on it with a five-second
     * budget, and Claude Code discards the answer when the budget runs out. On a desk that ran short
     * of memory (a container VM holding 25 GB), low memory priority made the daemon the first
     * process Windows paged out and low I/O priority made its page-ins the last served: a trivial
     * request took 4.9 seconds, the web page never loaded, and every prompt reported its hook had
     * timed out — while the sessions, started from a terminal at normal priority, carried on fine.
     */
    `$settings.Priority = 4`,
    `$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\\$env:USERNAME" -LogonType Interactive -RunLevel Limited`,
    `Register-ScheduledTask -TaskName '${TASK_NAMES[role]}' -Action $action -Trigger $trigger -Settings $settings -Principal $principal ` +
      `-Description '${role === 'daemon' ? 'Keeps the Switchboard daemon running for Claude Code agent coordination and subscription management.' : 'Keeps the Switchboard desk agent running, so this machine can host sessions for its hub.'}' -Force | Out-Null`,
    `'installed'`,
  ].join('; ');
  await ps(script);
  return serviceStatus(role);
}

export async function uninstallService(role: ServiceRole = 'daemon'): Promise<ServiceStatus> {
  if (IS_LINUX) return systemd.uninstall(role);
  if (!IS_WINDOWS) throw Object.assign(new Error('Automatic start is implemented for Windows Task Scheduler only.'), { status: 400 });
  await ps(`Unregister-ScheduledTask -TaskName '${TASK_NAMES[role]}' -Confirm:$false -ErrorAction SilentlyContinue`);
  fs.rmSync(files(role).launcher, { force: true });
  fs.rmSync(files(role).runner, { force: true });
  return serviceStatus(role);
}

/** Start the task now, so installing does not require a logout. */
export async function startService(role: ServiceRole = 'daemon'): Promise<ServiceStatus> {
  if (IS_LINUX) return systemd.start(role);
  if (!IS_WINDOWS) throw Object.assign(new Error('Automatic start is implemented for Windows Task Scheduler only.'), { status: 400 });
  await ps(`Start-ScheduledTask -TaskName '${TASK_NAMES[role]}'`);
  return serviceStatus(role);
}
