import { execFile } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { promisify } from 'node:util';
import { CLI_PATH, DATA_DIR, DAEMON_URL, IS_WINDOWS, ensureDirs } from '../config.ts';
import type { ServiceStatus } from '../shared/types.ts';

const run = promisify(execFile);

export const TASK_NAME = 'Switchboard daemon';
const LAUNCHER = path.join(DATA_DIR, 'switchboard-daemon.vbs');
const RUNNER = path.join(DATA_DIR, 'switchboard-daemon.cmd');
const LOG = path.join(DATA_DIR, 'daemon.log');

function ps(script: string): Promise<{ stdout: string; stderr: string }> {
  return run('powershell.exe', ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-Command', script], {
    timeout: 60_000,
    windowsHide: true,
  });
}

/**
 * A supervisor script rather than a bare command: it keeps the daemon hidden (no console window
 * on every logon) and restarts it if it ever exits. Task Scheduler's own restart-on-failure
 * cannot do this job, because a task that launches a detached process is considered finished
 * immediately.
 */
function launcherScript(): string {
  // Run the batch file, not the command directly: `cmd /c "quoted exe" ...` mangles its own
  // quoting, and a one-line batch file sidesteps the whole nested-quote problem.
  return [
    "' Generated by: switchboard service install",
    'Set sh = CreateObject("WScript.Shell")',
    'Do',
    `  sh.Run """${RUNNER}""", 0, True`,
    '  WScript.Sleep 10000',
    'Loop',
    '',
  ].join('\r\n');
}

function runnerScript(): string {
  return [
    '@echo off',
    'rem Generated by: switchboard service install',
    `echo [%date% %time%] starting switchboard daemon>> "${LOG}"`,
    `"${process.execPath}" "${CLI_PATH}" daemon >> "${LOG}" 2>&1`,
    `echo [%date% %time%] daemon exited with %ERRORLEVEL%>> "${LOG}"`,
    '',
  ].join('\r\n');
}

export async function serviceStatus(): Promise<ServiceStatus> {
  const status: ServiceStatus = {
    supported: IS_WINDOWS,
    installed: false,
    state: null,
    lastRunTime: null,
    lastResult: null,
    running: false,
    logPath: LOG,
  };
  try {
    const res = await fetch(`${DAEMON_URL}/healthz`, { signal: AbortSignal.timeout(2000) });
    status.running = res.ok;
  } catch {
    status.running = false;
  }
  if (!IS_WINDOWS) return status;
  try {
    const { stdout } = await ps(
      `$t = Get-ScheduledTask -TaskName '${TASK_NAME}' -ErrorAction SilentlyContinue; ` +
        `if ($t) { $i = $t | Get-ScheduledTaskInfo; ` +
        `@{ state = $t.State.ToString(); lastRunTime = $(if ($i.LastRunTime) { $i.LastRunTime.ToString('o') } else { $null }); lastResult = $i.LastTaskResult.ToString() } | ConvertTo-Json -Compress }`,
    );
    const text = stdout.trim();
    if (text) {
      const info = JSON.parse(text) as { state?: string; lastRunTime?: string; lastResult?: string };
      status.installed = true;
      status.state = info.state ?? null;
      status.lastRunTime = info.lastRunTime ?? null;
      status.lastResult = info.lastResult ?? null;
    }
  } catch {
    // Task Scheduler unavailable: report as not installed
  }
  return status;
}

/**
 * Register a logon task that keeps the daemon running.
 *
 * It is a *logon* task, not a startup one, on purpose: opening Windows Terminal tabs needs an
 * interactive desktop, which a session-0 service does not have. After an unattended reboot the
 * daemon therefore comes back when the desk signs in.
 */
export async function installService(delaySeconds = 20): Promise<ServiceStatus> {
  if (!IS_WINDOWS) throw Object.assign(new Error('Automatic start is implemented for Windows Task Scheduler only.'), { status: 400 });
  ensureDirs();
  fs.writeFileSync(RUNNER, runnerScript(), 'utf8');
  fs.writeFileSync(LAUNCHER, launcherScript(), 'utf8');
  const delay = `PT${Math.max(0, Math.round(delaySeconds))}S`;
  const script = [
    `$action = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument '"${LAUNCHER}"'`,
    `$trigger = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\\$env:USERNAME"`,
    `$trigger.Delay = '${delay}'`,
    // Never stop it: not on battery, not after 3 days, not when the machine looks idle.
    `$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable ` +
      `-ExecutionTimeLimit ([TimeSpan]::Zero) -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1) -MultipleInstances IgnoreNew`,
    `$settings.DisallowStartOnRemoteAppSession = $false`,
    `$settings.StopIfGoingOnBatteries = $false`,
    `$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\\$env:USERNAME" -LogonType Interactive -RunLevel Limited`,
    `Register-ScheduledTask -TaskName '${TASK_NAME}' -Action $action -Trigger $trigger -Settings $settings -Principal $principal ` +
      `-Description 'Keeps the Switchboard daemon running for Claude Code agent coordination and subscription management.' -Force | Out-Null`,
    `'installed'`,
  ].join('; ');
  await ps(script);
  return serviceStatus();
}

export async function uninstallService(): Promise<ServiceStatus> {
  if (!IS_WINDOWS) throw Object.assign(new Error('Automatic start is implemented for Windows Task Scheduler only.'), { status: 400 });
  await ps(`Unregister-ScheduledTask -TaskName '${TASK_NAME}' -Confirm:$false -ErrorAction SilentlyContinue`);
  fs.rmSync(LAUNCHER, { force: true });
  fs.rmSync(RUNNER, { force: true });
  return serviceStatus();
}

/** Start the task now, so installing does not require a logout. */
export async function startService(): Promise<ServiceStatus> {
  if (!IS_WINDOWS) throw Object.assign(new Error('Automatic start is implemented for Windows Task Scheduler only.'), { status: 400 });
  await ps(`Start-ScheduledTask -TaskName '${TASK_NAME}'`);
  return serviceStatus();
}
