import { execFile } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import { CLI_PATH, DATA_DIR, ensureDirs } from '../config.ts';
import type { ServiceStatus } from '../shared/types.ts';

const run = promisify(execFile);

/*
 * Always on, on Linux: a systemd user unit, started at boot.
 *
 * Windows can only start the daemon at logon, because opening terminal tabs needs an interactive
 * desktop. Linux has no such limit: with lingering enabled, systemd starts the user's own service
 * manager when the machine boots, before anybody signs in, and that starts this unit. Sessions
 * opened while nobody is signed in go into detached tmux sessions (see the launcher), and the web
 * terminal drives them as it drives any other.
 *
 * KillMode=process is what keeps sessions alive across a restart of the agent or the daemon: the
 * tmux server and every claude in it are children of the unit, and the default would take them all
 * down with it. On Windows, runners outlive the daemon the same way.
 */

export type Role = 'daemon' | 'desk';

export function unitName(role: Role): string {
  return `switchboard-${role}.service`;
}

function unitFile(role: Role): string {
  const config = process.env.XDG_CONFIG_HOME || path.join(os.homedir(), '.config');
  return path.join(config, 'systemd', 'user', unitName(role));
}

export function logFile(role: Role): string {
  return path.join(DATA_DIR, `${role}.log`);
}

/** systemd's quoting for one word on an ExecStart line. */
function quote(word: string): string {
  return `"${word.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

export function unitText(role: Role, env: NodeJS.ProcessEnv = process.env): string {
  const lines = [
    '# Generated by: switchboard service install',
    '[Unit]',
    role === 'desk' ? 'Description=Switchboard desk agent (hosts Claude Code sessions for its hub)' : 'Description=Switchboard daemon',
    // Never give up: a hub that is unreachable for an hour is retried for as long as it takes.
    'StartLimitIntervalSec=0',
    '',
    '[Service]',
    'Type=simple',
    `ExecStart=${[process.execPath, CLI_PATH, role].map(quote).join(' ')}`,
    `WorkingDirectory=${DATA_DIR}`,
    // The PATH this was installed from, so claude, git, gh, az and tmux are found as they were then.
    `Environment=${quote(`PATH=${env.PATH ?? '/usr/local/bin:/usr/bin:/bin'}`)}`,
  ];
  // Whatever of Switchboard's own settings the install was made with, the service keeps.
  for (const key of ['SWITCHBOARD_DATA_DIR', 'SWITCHBOARD_TERMINAL', 'SWITCHBOARD_HUB_URL', 'SWITCHBOARD_BIND', 'SWITCHBOARD_PORT']) {
    if (env[key]) lines.push(`Environment=${quote(`${key}=${env[key]}`)}`);
  }
  lines.push(
    'Restart=always',
    'RestartSec=5',
    'KillMode=process',
    `StandardOutput=append:${logFile(role)}`,
    `StandardError=append:${logFile(role)}`,
    '',
    '[Install]',
    'WantedBy=default.target',
    '',
  );
  return lines.join('\n');
}

async function systemctl(...args: string[]): Promise<string> {
  const { stdout } = await run('systemctl', ['--user', ...args], { timeout: 30_000 });
  return stdout.trim();
}

/** Whether the user's service manager is started at boot, without anybody signing in. */
async function lingering(): Promise<boolean> {
  try {
    const { stdout } = await run('loginctl', ['show-user', os.userInfo().username, '-p', 'Linger', '--value'], { timeout: 10_000 });
    return stdout.trim() === 'yes';
  } catch {
    return false;
  }
}

export async function status(role: Role): Promise<ServiceStatus> {
  const s: ServiceStatus = { supported: true, installed: fs.existsSync(unitFile(role)), state: null, lastRunTime: null, lastResult: null, running: false, logPath: logFile(role) };
  if (!s.installed) return s;
  try {
    const out = await systemctl('show', unitName(role), '-p', 'ActiveState', '-p', 'SubState', '-p', 'ExecMainStartTimestamp', '-p', 'Result', '-p', 'UnitFileState');
    const kv = Object.fromEntries(out.split('\n').map((l) => [l.slice(0, l.indexOf('=')), l.slice(l.indexOf('=') + 1)]));
    const linger = await lingering();
    s.running = kv.ActiveState === 'active';
    s.state = `${kv.ActiveState}/${kv.SubState}, ${kv.UnitFileState}${linger ? ', starts at boot' : ', starts at login only (run: loginctl enable-linger)'}`;
    s.lastRunTime = kv.ExecMainStartTimestamp || null;
    s.lastResult = kv.Result || null;
  } catch {
    // systemctl --user unavailable (no user manager in this shell): report what is on disk
  }
  return s;
}

export async function install(role: Role): Promise<{ status: ServiceStatus; notes: string[] }> {
  ensureDirs();
  const notes: string[] = [];
  const other: Role = role === 'daemon' ? 'desk' : 'daemon';
  // One role per machine.
  if (fs.existsSync(unitFile(other))) {
    await systemctl('disable', '--now', unitName(other)).catch(() => undefined);
    fs.rmSync(unitFile(other), { force: true });
  }
  fs.mkdirSync(path.dirname(unitFile(role)), { recursive: true });
  fs.writeFileSync(unitFile(role), unitText(role));
  await systemctl('daemon-reload');
  await systemctl('enable', unitName(role));
  await systemctl('restart', unitName(role));
  if (!(await lingering())) {
    try {
      await run('loginctl', ['enable-linger', os.userInfo().username], { timeout: 15_000 });
    } catch {
      notes.push(`To start at boot without anybody signing in, run once: sudo loginctl enable-linger ${os.userInfo().username}`);
    }
  }
  try {
    await run('tmux', ['-V'], { timeout: 5000 });
  } catch {
    notes.push('tmux is not installed. Sessions opened while nobody is signed in need it: sudo pacman -S tmux (or your distribution\'s equivalent).');
  }
  return { status: await status(role), notes };
}

export async function uninstall(role: Role): Promise<ServiceStatus> {
  await systemctl('disable', '--now', unitName(role)).catch(() => undefined);
  fs.rmSync(unitFile(role), { force: true });
  await systemctl('daemon-reload').catch(() => undefined);
  return status(role);
}

export async function start(role: Role): Promise<ServiceStatus> {
  await systemctl('restart', unitName(role));
  return status(role);
}
